### ISSUE TITLE
ERROR: The system cannot find the specific path.

### ISSUE THREAD

**Issue by krishnakoumar27** [Vijayabhaskar96/CSAimBot#1]
When I ran the command `python Run_Me.py --resize 3 --score 0.50 --show False --input mouse --shoot HEAD --duration 0.2` it returns the error as "The system cannot find the path specified."

Tensorflow version: 2.2.0 with GPU 

Log from the Command Prompt:

`Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "Run_Me.py", line 100, in <module>
    serialized_graph = fid.read()
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 116, in read
    self._preread_check()
  File "C:\Users\krish\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 79, in _preread_check
    self.__name, 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\krish\Downloads\CSAimBot-master\object_detection\ssd_mobilenet_v1_coco_11_06_2017\frozen_inference_graph.pb : The system cannot find the path specified.
; No such process`

**Comment by Vijayabhaskar96** [comment]
You need to download ssd_mobilenet_v1_coco_11_06_2017 files, anyway I don't think it will with Tensorflow 2. It's an old project.

**Comment by krishnakoumar27** [comment]
Thank you for the reply. I just found out that the file 'frozen_inference_graph.pb' is compatible with Tensorflow 1.2
